# Generated by Django 4.0 on 2021-12-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_alter_type_options_employee_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='categ',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='type',
        ),
    ]
